version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: database
  
  backend:
    build:
      context: ./backend
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn DRM_proj.wsgi 0.0.0.0:8080"
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx